//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CondIn.OK_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="OK_Service.WS_ISIntegrationSoap")]
    public interface WS_ISIntegrationSoap {
        
        // CODEGEN: Параметр "Err" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Err")]
        CondIn.OK_Service.UploadFileResponse UploadFile(CondIn.OK_Service.UploadFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UploadFile", ReplyAction="*")]
        System.Threading.Tasks.Task<CondIn.OK_Service.UploadFileResponse> UploadFileAsync(CondIn.OK_Service.UploadFileRequest request);
        
        // CODEGEN: Параметр "GetResult" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlArrayItemAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        CondIn.OK_Service.GetResponse Get(CondIn.OK_Service.GetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get", ReplyAction="*")]
        System.Threading.Tasks.Task<CondIn.OK_Service.GetResponse> GetAsync(CondIn.OK_Service.GetRequest request);
        
        // CODEGEN: Параметр "Err" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Set", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Err")]
        CondIn.OK_Service.SetResponse Set(CondIn.OK_Service.SetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Set", ReplyAction="*")]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetResponse> SetAsync(CondIn.OK_Service.SetRequest request);
        
        // CODEGEN: Параметр "Err" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAsync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Err")]
        CondIn.OK_Service.SetAsyncResponse SetAsync(CondIn.OK_Service.SetAsyncRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAsync", ReplyAction="*")]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetAsyncResponse> SetAsyncAsync(CondIn.OK_Service.SetAsyncRequest request);
        
        // CODEGEN: Параметр "Err" требует дополнительной информации о схеме, которую невозможно получить в режиме параметров. Указан атрибут "System.Xml.Serialization.XmlElementAttribute".
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAsync_ResultGet", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="Err")]
        CondIn.OK_Service.SetAsync_ResultGetResponse SetAsync_ResultGet(CondIn.OK_Service.SetAsync_ResultGetRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetAsync_ResultGet", ReplyAction="*")]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetAsync_ResultGetResponse> SetAsync_ResultGetAsync(CondIn.OK_Service.SetAsync_ResultGetRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultService : ResultRow {
        
        private string statusField;
        
        private string textField;
        
        private string dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ResultService))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRow : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ResultRowField[] fieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Field", Order=0)]
        public ResultRowField[] Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
                this.RaisePropertyChanged("Field");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ResultRowField : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string valueField;
        
        private string nameField;
        
        private ProcedureFieldType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public ProcedureFieldType Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public enum ProcedureFieldType {
        
        /// <remarks/>
        STRING,
        
        /// <remarks/>
        GUID,
        
        /// <remarks/>
        INT,
        
        /// <remarks/>
        DECIMAL,
        
        /// <remarks/>
        DATETIME,
        
        /// <remarks/>
        IMAGE,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFile", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] file;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string fileName;
        
        public UploadFileRequest() {
        }
        
        public UploadFileRequest(string login, string password, byte[] file, string fileName) {
            this.login = login;
            this.password = password;
            this.file = file;
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UploadFileResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UploadFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CondIn.OK_Service.ResultService Err;
        
        public UploadFileResponse() {
        }
        
        public UploadFileResponse(CondIn.OK_Service.ResultService Err) {
            this.Err = Err;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Get", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Procedure;
        
        public GetRequest() {
        }
        
        public GetRequest(string login, string pass, string Procedure) {
            this.login = login;
            this.pass = pass;
            this.Procedure = Procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ResultRow")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Field", IsNullable=false, NestingLevel=1)]
        public CondIn.OK_Service.ResultRowField[][] GetResult;
        
        public GetResponse() {
        }
        
        public GetResponse(CondIn.OK_Service.ResultRowField[][] GetResult) {
            this.GetResult = GetResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Set", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string Procedure;
        
        public SetRequest() {
        }
        
        public SetRequest(string login, string pass, string Procedure) {
            this.login = login;
            this.pass = pass;
            this.Procedure = Procedure;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CondIn.OK_Service.ResultService Err;
        
        public SetResponse() {
        }
        
        public SetResponse(CondIn.OK_Service.ResultService Err) {
            this.Err = Err;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAsync", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetAsyncRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ProcedureName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string Data;
        
        public SetAsyncRequest() {
        }
        
        public SetAsyncRequest(string login, string pass, string ProcedureName, string Data) {
            this.login = login;
            this.pass = pass;
            this.ProcedureName = ProcedureName;
            this.Data = Data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAsyncResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetAsyncResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CondIn.OK_Service.ResultService Err;
        
        public SetAsyncResponse() {
        }
        
        public SetAsyncResponse(CondIn.OK_Service.ResultService Err) {
            this.Err = Err;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAsync_ResultGet", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetAsync_ResultGetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string login;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string pass;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string guid;
        
        public SetAsync_ResultGetRequest() {
        }
        
        public SetAsync_ResultGetRequest(string login, string pass, string guid) {
            this.login = login;
            this.pass = pass;
            this.guid = guid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SetAsync_ResultGetResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SetAsync_ResultGetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CondIn.OK_Service.ResultService Err;
        
        public SetAsync_ResultGetResponse() {
        }
        
        public SetAsync_ResultGetResponse(CondIn.OK_Service.ResultService Err) {
            this.Err = Err;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_ISIntegrationSoapChannel : CondIn.OK_Service.WS_ISIntegrationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_ISIntegrationSoapClient : System.ServiceModel.ClientBase<CondIn.OK_Service.WS_ISIntegrationSoap>, CondIn.OK_Service.WS_ISIntegrationSoap {
        
        public WS_ISIntegrationSoapClient() {
        }
        
        public WS_ISIntegrationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_ISIntegrationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ISIntegrationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_ISIntegrationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondIn.OK_Service.UploadFileResponse CondIn.OK_Service.WS_ISIntegrationSoap.UploadFile(CondIn.OK_Service.UploadFileRequest request) {
            return base.Channel.UploadFile(request);
        }
        
        public CondIn.OK_Service.ResultService UploadFile(string login, string password, byte[] file, string fileName) {
            CondIn.OK_Service.UploadFileRequest inValue = new CondIn.OK_Service.UploadFileRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.file = file;
            inValue.fileName = fileName;
            CondIn.OK_Service.UploadFileResponse retVal = ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).UploadFile(inValue);
            return retVal.Err;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CondIn.OK_Service.UploadFileResponse> CondIn.OK_Service.WS_ISIntegrationSoap.UploadFileAsync(CondIn.OK_Service.UploadFileRequest request) {
            return base.Channel.UploadFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<CondIn.OK_Service.UploadFileResponse> UploadFileAsync(string login, string password, byte[] file, string fileName) {
            CondIn.OK_Service.UploadFileRequest inValue = new CondIn.OK_Service.UploadFileRequest();
            inValue.login = login;
            inValue.password = password;
            inValue.file = file;
            inValue.fileName = fileName;
            return ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).UploadFileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondIn.OK_Service.GetResponse CondIn.OK_Service.WS_ISIntegrationSoap.Get(CondIn.OK_Service.GetRequest request) {
            return base.Channel.Get(request);
        }
        
        public CondIn.OK_Service.ResultRowField[][] Get(string login, string pass, string Procedure) {
            CondIn.OK_Service.GetRequest inValue = new CondIn.OK_Service.GetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.Procedure = Procedure;
            CondIn.OK_Service.GetResponse retVal = ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).Get(inValue);
            return retVal.GetResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CondIn.OK_Service.GetResponse> CondIn.OK_Service.WS_ISIntegrationSoap.GetAsync(CondIn.OK_Service.GetRequest request) {
            return base.Channel.GetAsync(request);
        }
        
        public System.Threading.Tasks.Task<CondIn.OK_Service.GetResponse> GetAsync(string login, string pass, string Procedure) {
            CondIn.OK_Service.GetRequest inValue = new CondIn.OK_Service.GetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.Procedure = Procedure;
            return ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).GetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondIn.OK_Service.SetResponse CondIn.OK_Service.WS_ISIntegrationSoap.Set(CondIn.OK_Service.SetRequest request) {
            return base.Channel.Set(request);
        }
        
        public CondIn.OK_Service.ResultService Set(string login, string pass, string Procedure) {
            CondIn.OK_Service.SetRequest inValue = new CondIn.OK_Service.SetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.Procedure = Procedure;
            CondIn.OK_Service.SetResponse retVal = ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).Set(inValue);
            return retVal.Err;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetResponse> CondIn.OK_Service.WS_ISIntegrationSoap.SetAsync(CondIn.OK_Service.SetRequest request) {
            return base.Channel.SetAsync(request);
        }
        
        public System.Threading.Tasks.Task<CondIn.OK_Service.SetResponse> SetAsync(string login, string pass, string Procedure) {
            CondIn.OK_Service.SetRequest inValue = new CondIn.OK_Service.SetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.Procedure = Procedure;
            return ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).SetAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondIn.OK_Service.SetAsyncResponse CondIn.OK_Service.WS_ISIntegrationSoap.SetAsync(CondIn.OK_Service.SetAsyncRequest request) {
            return base.Channel.SetAsync(request);
        }
        
        public CondIn.OK_Service.ResultService SetAsync(string login, string pass, string ProcedureName, string Data) {
            CondIn.OK_Service.SetAsyncRequest inValue = new CondIn.OK_Service.SetAsyncRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.ProcedureName = ProcedureName;
            inValue.Data = Data;
            CondIn.OK_Service.SetAsyncResponse retVal = ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).SetAsync(inValue);
            return retVal.Err;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetAsyncResponse> CondIn.OK_Service.WS_ISIntegrationSoap.SetAsyncAsync(CondIn.OK_Service.SetAsyncRequest request) {
            return base.Channel.SetAsyncAsync(request);
        }
        
        public System.Threading.Tasks.Task<CondIn.OK_Service.SetAsyncResponse> SetAsyncAsync(string login, string pass, string ProcedureName, string Data) {
            CondIn.OK_Service.SetAsyncRequest inValue = new CondIn.OK_Service.SetAsyncRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.ProcedureName = ProcedureName;
            inValue.Data = Data;
            return ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).SetAsyncAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CondIn.OK_Service.SetAsync_ResultGetResponse CondIn.OK_Service.WS_ISIntegrationSoap.SetAsync_ResultGet(CondIn.OK_Service.SetAsync_ResultGetRequest request) {
            return base.Channel.SetAsync_ResultGet(request);
        }
        
        public CondIn.OK_Service.ResultService SetAsync_ResultGet(string login, string pass, string guid) {
            CondIn.OK_Service.SetAsync_ResultGetRequest inValue = new CondIn.OK_Service.SetAsync_ResultGetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.guid = guid;
            CondIn.OK_Service.SetAsync_ResultGetResponse retVal = ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).SetAsync_ResultGet(inValue);
            return retVal.Err;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CondIn.OK_Service.SetAsync_ResultGetResponse> CondIn.OK_Service.WS_ISIntegrationSoap.SetAsync_ResultGetAsync(CondIn.OK_Service.SetAsync_ResultGetRequest request) {
            return base.Channel.SetAsync_ResultGetAsync(request);
        }
        
        public System.Threading.Tasks.Task<CondIn.OK_Service.SetAsync_ResultGetResponse> SetAsync_ResultGetAsync(string login, string pass, string guid) {
            CondIn.OK_Service.SetAsync_ResultGetRequest inValue = new CondIn.OK_Service.SetAsync_ResultGetRequest();
            inValue.login = login;
            inValue.pass = pass;
            inValue.guid = guid;
            return ((CondIn.OK_Service.WS_ISIntegrationSoap)(this)).SetAsync_ResultGetAsync(inValue);
        }
    }
}
